### PR TITLE
fix: properly handle tab indentation

### PR DESCRIPTION
**Pull request by zachhardesty7**
(this is the correct branch clone of #24)

Hi, incredibly useful extension but it doesn't work when using tab indentation. figured I'd go ahead and contribute the fix back. Also updated some very out of date packages and added a simple new test to validate this. Let me know if you want anything changed! Thanks!

### CODE REVIEW

**Comment by tnrich** [comment]
@ZachGawlik merge this? What's the status of this extension?

**Comment by ZachGawlik** [comment]
My apologies for not seeing this earlier. Thanks for the great contribution! And thanks also tnrich for the ping.

(p.s. I made a slight tweak since it looks like your npm is configured to have a different default registry)

**Comment by ZachGawlik** [comment]
The update is published as [v1.1.0 in the VSCode Extension Marketplace](https://marketplace.visualstudio.com/items?itemName=zachgawlik.convert-object-to-jsx). Now that I've become reacquainted with this repo for the first time in 4 years, I'll do a bit of dusting off 😅 . 

Thanks again!

**Comment by tnrich** [comment]
@ZachGawlik haha glad to see you're still around. I had assumed this repo was deprecated. 

A heads up that I've forked your repo and am publishing updates off of my branch. 

I've noticed a few issues that I'm fixing there. Feel free to steal those changes back to your repo if you want them, or not. 

Issue 1 - your version seems to be greedy with including the entire line into a selected region. I don't want this functionality unless I have no selection at all. 

Issue 2 - the splitProps function seems like it is basing its detection of props based on indentation level. While this can work well in some cases, it seems also can cause a ton of flake if the selection is not uniform or if the indentation isn't perfect. I'm changing splitProps in my version to use a different way of detecting distinct props. 

Cheers and thanks for the great repo!

**Pull request merged**
